name: CI/CD for React App

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.12.0'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Check Directory and Deploy to EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem
          chmod 600 private-key.pem
          ssh -i private-key.pem -o StrictHostKeyChecking=no ec2-user@3.109.3.200 << 'EOF'
          if [ -d "/home/ec2-user/myapp" ]; then
          echo "Directory exists"
          else
          echo "Directory does not exist, creating it now"
          mkdir -p /home/ec2-user/myapp
          fi
          cd /home/ec2-user/myapp
          # Add your deploy commands here
          EOF



     


        # uses: appleboy/ssh-action@v0.1.3
        # with:
        #   host: ${{ secrets.EC2_HOST }}
        #   username: ec2-user
        #   key: ${{ secrets.SSH_PRIVATE_KEY }} 
        #   port: 22
        #   script: |

        # - name: Deploy to EC2
        #run: |
        #  echo "${{ secrets.SSH_PRIVATE_KEY }}" > private-key.pem
         # chmod 600 private-key.pem
         # ssh -i private-key.pem -o StrictHostKeyChecking=no ec2-user@3.109.3.200
         # cd /home/ec2-user/myapp
       #  pwd
       #   git pull origin main
        #  npm install
       #   npm run build
       #   pm2 restart all
