name: CI/CD for React Application

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: build/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: react-build

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/privatekey.pem
          chmod 600 ~/.ssh/privatekey.pem
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          scp -i ~/.ssh/privatekey.pem -o StrictHostKeyChecking=no -r build/* $USER@$HOST:/path/to/your/app
          ssh -i ~/.ssh/privatekey.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            ls -al /path/to/your/app
            cd /path/to/your/app
            sudo systemctl restart nginx
            echo "Deployment Completed!"
          EOF
