name: CI/CD Workflow with Dropdown

on:
  workflow_dispatch: # Enables manual trigger with dropdown input
    inputs:
      environment:
        description: "Choose the deployment environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - production

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log Environment Selection
        run: echo "Selected environment: ${{ github.event.inputs.environment }}"

      - name: Install Dependencies
        run: |
          yarn install
          yarn build

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t dropdown-app:${{ github.event.inputs.environment }} .
          docker tag dropdown-app:${{ github.event.inputs.environment }} ${{ steps.login-ecr.outputs.registry }}/dropdown-app:${{ github.event.inputs.environment }}
          docker push ${{ steps.login-ecr.outputs.registry }}/dropdown-app:${{ github.event.inputs.environment }}

        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy to ECS
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment"
          aws ecs update-service --cluster <your-cluster-name> \
                                 --service <your-service-name> \
                                 --force-new-deployment
